import type { Metadata } from "next";
import { Rubik, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import { Provider } from "../utils/provider";
// import { AppWrapper } from "../context/index";

import { getTheme } from "../utils/getTheme";

const rubik600 = Rubik({
  subsets: ["latin"],
  weight: "600",
  variable: "--font-rubik600",
});

const robotomono200 = Roboto_Mono({
  subsets: ["latin"],
  weight: "200",
  variable: "--font-robotomono200",
});
const robotomono400 = Roboto_Mono({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-robotomono400",
});
const robotomono600 = Roboto_Mono({
  subsets: ["latin"],
  weight: "600",
  variable: "--font-robotomono600",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script dangerouslySetInnerHTML={{ __html: getTheme }} />
      </head>
      <body
        className={`${rubik600.variable} ${robotomono200.variable} ${robotomono400.variable} ${robotomono600.variable} selection:-bg-purple-500`}
      >
        <Provider>
          {/* <AppWrapper> */}
          <Navbar />
          <main>{children}</main>
          {/* </AppWrapper> */}
        </Provider>
      </body>
    </html>
  );
}
